export const APP_LOAD = 'APP_LOAD';
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';
export const ARTICLE_PAGE_LOADED = 'ARTICLE_PAGE_LOADED';
export const ARTICLE_PAGE_UNLOADED = 'ARTICLE_PAGE_UNLOADED';
export const SET_PAGE = 'SET_PAGE';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';